import { Inter, Nunito, Roboto } from 'next/font/google'
import './globals.css'
import '../public/template/css/sb-admin-2.css'
import '../public/template/css/fontawesome-free/css/all.min.css'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
 
    <body id="page-top" className={nunito.className}>
    
        <div id="wrapper">
    
            <ul className="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    

                <a className="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                    <div className="sidebar-brand-icon rotate-n-15">
                        <i className="fas fa-laugh-wink"></i>
                    </div>
                    <div className="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
                </a>
    
                <hr className="sidebar-divider my-0" />
    
                <li className="nav-item active">
                    <a className="nav-link" href="/">
                        <i className="fas fa-home"></i>
                        <span>Home</span></a>
                </li>
    
                <hr className="sidebar-divider" />
    

                <div className="sidebar-heading">
                    Menu
                </div>
    
                <li className="nav-item">
                    <a className="nav-link" href="/usuario">
                        <i className="fas fa-fw fa-user"></i>
                        <span>Usuarios</span>
                    </a>
                </li>
                <li className="nav-item">
                <a className="nav-link" href="/imovel">
                        <i className="fas fa-fw fa-build"></i>
                        <span>Imóveis</span>
                    </a>
                </li>


                <hr className="sidebar-divider d-none d-md-block" />
    
                <div className="text-center d-none d-md-inline">
                    <button className="rounded-circle border-0" id="sidebarToggle"></button>
                </div>
  
    
            </ul>

            <div id="content-wrapper" className="d-flex flex-column">
    
                <div id="content">
    
                    <nav className="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    
                        <button id="sidebarToggleTop" className="btn btn-link d-md-none rounded-circle mr-3">
                            <i className="fa fa-bars"></i>
                        </button>

                        <ul className="navbar-nav ml-auto">
    
                            <div className="topbar-divider d-none d-sm-block"></div>
    

                            <li className="nav-item dropdown no-arrow">
                                <a className="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span className="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                    <img className="img-profile rounded-circle"
                                        src="/img/avatar.png" />
                                </a>

                                <div className="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                    aria-labelledby="userDropdown">
                                    <a className="dropdown-item" href="#">
                                        <i className="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Profile
                                    </a>
                                    <a className="dropdown-item" href="#">
                                        <i className="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Settings
                                    </a>
                                    <a className="dropdown-item" href="#">
                                        <i className="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Activity Log
                                    </a>
                                    <div className="dropdown-divider"></div>
                                    <a className="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                        <i className="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Logout
                                    </a>
                                </div>
                            </li>
    
                        </ul>
    
                    </nav>
    
                    <div className="container-fluid">
                      {children}
                    </div>   
                </div>   
                <footer className="sticky-footer bg-white">
                    <div className="container my-auto">
                        <div className="copyright text-center my-auto">
                            <span>Copyright &copy; Your Website 2021</span>
                        </div>
                    </div>
                </footer>
    
            </div>
    
        </div>
    
        <a className="scroll-to-top rounded" href="#page-top">
            <i className="fas fa-angle-up"></i>
        </a>

        <div className="modal fade" id="logoutModal" tabIndex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div className="modal-dialog" role="document">
                <div className="modal-content">
                    <div className="modal-header">
                        <h5 className="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                        <button className="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div className="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                    <div className="modal-footer">
                        <button className="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a className="btn btn-primary" href="login.html">Logout</a>
                    </div>
                </div>
            </div>
        </div>
    
        <script src="/template/js/jquery/jquery.min.js"></script>
        <script src="/template/js/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="/template/js/sb-admin-2.js"></script>
    </body>
    
    </html>
  )
}
